spring:
  datasource:
    url: jdbc:mysql://192.168.0.94:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost
